### ISSUE TITLE
Unable to sign with blank mode

### ISSUE THREAD

**Issue by abeverley** [flowerysong/OpenARC#1]
Just a quick one whilst I remember (I've not investigated further). I tried using the `main` branch from this repo, and I found that when the `Mode` is blank (i.e. automatic), that openarc aborts with a segfault about the selector being null (even though it is set in the config). I'm not sure whether this is a new bug in this branch, or whether it is an old bug and the fix hasn't been merged. It works as expected on the upstream `develop` branch.

**Comment by flowerysong** [comment]
This is a bug introduced by https://github.com/trusteddomainproject/OpenARC/pull/159, it should be fixed in 20df719c570e17b84650134e7d56af8a14d5e670
