### ISSUE TITLE
Will it work on Debian 12 ?

### ISSUE THREAD

**Issue by lucas-oliver-trondsen** [flowerysong/OpenARC#2]
Thank you for this fork! Since the original [OpenARC](https://github.com/trusteddomainproject/OpenARC) project seems to be abandoned, I'd want to compile OpenARC from your fork and install it on Debian 12. Do you think it will work ? Should I pay any attention to the issue mentioned [here](https://github.com/trusteddomainproject/OpenARC/issues/174) ?

**Comment by flowerysong** [comment]
It's kind of an edge case that most people won't run into in their deployments, but now that I've had a chance to review it that change looks like it should be made in libopenarc rather than the milter. See https://github.com/flowerysong/OpenARC/commit/9dc8658366b9b3cadbed09754fdf1a7e5cd61e47

There's no reason this fork shouldn't work on Debian 12; it includes all of the patches that I'm aware of from distro packages.

**Comment by lucas-oliver-trondsen** [comment]
Thank you so much, flowerysong! I greatly appreciate your work.

There is so little information about installing OpenARC in general. A few days ago I managed to install the packaged version published [here](https://download.opensuse.org/repositories/home:/andreasschulze/Debian_11/). It worked, but I don't want to use on Debian 12 an unofficial package built for Debian 11 and hosted in an openSUSE repository. There is indeed an official Debian package but it's only included in the 'experimental' Debian repository and I found that it can't be installed on Debian 12 because of some dependency issues. So, I'll compile your version and install it on Debian 12 and I'll get back with my results, to close this thread. Thank you again!

**Comment by lucas-oliver-trondsen** [comment]
When I run:
```
autoreconf -fvi
./configure
```
I get at the end:
```
checking for milter library and includes... configure: error: milter not found
```
And I can't run `make` followed by `make install`.

I looked inside the `configure.ac` file and in the `# libmilter` section it seems that it looks for the file `mfapi.h` in `/usr/local/include/libmilter` and `/opt/local/include/libmilter` and `/usr/include/libmilter`. I don't have either of those 3 directories. I understand that `mfapi.h` is part of the `libmilter` that gets installed when Sendmail is installed, but I don't have Sendmail installed, since I use Postfix.

If I check to see if I have any `libmilter` installed:
```
dpkg --get-selections | grep libmilter
```
I get:
```
libmilter1.0.1:amd64				install
```
So, it seems that I only have '/usr/lib/x86_64-linux-gnu/libmilter.so.1.0.1', which is not what `configure.ac` is looking for.

**Comment by flowerysong** [comment]
Since you're compiling software you need the -dev package, which will contain the headers.

**Comment by flowerysong** [comment]
https://salsa.debian.org/debian/openarc/-/blob/master/debian/control?ref_type=heads#L6-L11

**Comment by lucas-oliver-trondsen** [comment]
Thank you, flowerysong. Indeed, after I installed `libmilter-dev`, I could run `./configure`, then `make` and `make install` without errors. Then I configured OpenARC and it seems to work ok. When I send test emails to echo@openarc.org I get back:

```
ARC-Seal: i=2; a=rsa-sha256; d=dahlem.somaf.de; s=arc1; t=1728162764;
	cv=pass; b=AFyn2Q/Pd3YnP6v3qpdiEL7oomOr8FSNoQFSRCwbm+2tSDwoe4iT69XQTDnfQH6tFNqh8eaotIPtYZ8v7PJP6eBnD5jpQUXJGhWjzRoM9s2xyl0vEBjSetNruUUSMRMjMjPXKKZnHnZ90euJke1pnzyNF8w0JPgHmSm2MYdwA1QmeGNLK7GAsmrBkv1yIQ19/dZIs8OrFc9BmWeb0U+Dtn5RFZW2oyQIQHon5p3Jrl+JGOA4fHkqW7fOUQ74qGyq4767gWAD6jMJcNQDct4N8n1TEz+Enwl1TFq8meAclb8iUcRMfFc9dlBEKxCxgfb8n8Mo//kEVrUTJ0vk7h9Uzg==
ARC-Message-Signature: i=2; a=rsa-sha256; d=dahlem.somaf.de; s=arc1;
	t=1728162764; c=relaxed/relaxed;
	bh=OiPOiQVuNdQyJqpTUBa9iiCffzRX7AxNP4iHdcMZoMU=;
	h=X-purgate-ID:X-purgate-size:X-purgate:X-purgate:X-purgate-Ad:
	 X-purgate-type:ARC-Message-Signature:ARC-Authentication-Results:
	 DKIM-Filter:DKIM-Signature:Received:Content-Type:Message-ID:Date:
	 MIME-Version:Content-Language:To:From:Subject; b=MRy+eM0GI9Y46gU0dOvNbWFzfszexIOz8PJAhH3LJ5pHDObsAcDFNGPggSn4roz+Hb++oo2WSpftNxFbO9BcnTCLzNNkneO8k5gSaLUVSrKGi23ZXCYxOukMVi8SO4tcWgGqH5PYOo9CmQ70CpfiJL8vULyV/KSM/4BAO86aF5Kg2yntCun2I4BiDhstIhU7J0BNFSPXSxYClsW4ggumpWwjujV1K5Hn9Abi3S+YJC6PrXYQNJnT5UQc/F2InE9IMwol8WHWZfSR76AcsDqN0LLc14FBvhbg0c40kDUw3eV0rZhN9r+tylKOEb+McCJnrIvQTPh2aVjnG91ffdCPcA==
ARC-Authentication-Results: i=2; dahlem.somaf.de; dmarc=pass (p=reject dis=none) header.from=mydomain.com; 
	spf=pass smtp.mailfrom=mydomain.com; 
	arc=pass smtp.remote-ip=my_server_IP_address; 
	dkim=pass (2048-bit key; secure) header.d=mydomain.com header.i=@mydomain.com header.a=rsa-sha256 header.s=default header.b=k7DVgDDH
```
When I send to a Protonmail email address, I also get `arc=pass` in the email received in Protonmail.

However, since ARC signatures can be forged, I think it's wise to accept ARC signatures only from a list of some specific domains which are well known for properly sealing their outbound modified emails.

So, now I have a different problem. How can I add a list with trusted ARC sealer domains, like [this list](https://github.com/trusteddomainproject/ARC_Community_Sealers/blob/master/community_sealer_whitelist) to OpenARC ? How can I make OpenARC use that list to trust the mentioned domains and accept ARC signatures only from those domains ? This means that when emails come in, and their SPF and DKIM verification fails because they were forwarded by mailing lists and the original emails were modified in transit, my mail server looks if the ARC signatures are ok, and if it finds that they are ok and they come from one of the trusted domains on that list, it accepts the emails, otherwise, my mail server doesn't take into account ARC signatures.

Do I have to make some changes in `/etc/openarc/openarc.conf` ? Should I implement some `check_sender_access hash` or some `check_policy_service` in `/etc/postfix/main.cf` ?

**Comment by flowerysong** [comment]
OpenARC does not implement any sort of policy engine, it's strictly concerned with evaluating and extending ARC chains, and making information about the chain state available for anything (like a local filter with logic about trusting specific domains) that wishes to consume it.

It wouldn't necessarily be unreasonable to implement that sort of thing in this project, but it's not functionality that currently exists.

**Comment by lucas-oliver-trondsen** [comment]
Thank you. Are you using OpenARC with Postfix ?

As it is now, I can use OpenARC to add ARC signatures to outgoing emails. This is OK.

I can also use OpenARC to verify the ARC signatures of incoming emails and add the proper headers to such emails. This is also OK, but what is the mechanism that shoulod be used to take action based on valid ARC signatures ? How can I accept incoming emails in spite of broken DKIM signatures, if the ARC chain gets verified ? Should this be implemented in Postfix or in some DNS settings ?

There is no documentation anywhere on how to actually use OpenARC for incoming emails. As if this is a state secret. I'm asking here because the official repository seems to be completely abandoned.

**Comment by lucas-oliver-trondsen** [comment]
I'll answer myself: The mechanism used by the receiving mail server to take action based on valid ARC signatures added by trusted intermediate mail servers to incoming emails, is implemented in **OpenDMARC**. In the `/etc/opendmarc.conf` file, the following lines should be added above the `##  Socket socketspec` line:

```
##  DomainWhitelistFile path
##      default (none)
##
##  A comprehensive list of whitelisted domains for which ARC signature headers
##  are trusted as determined by evaluating entries in the "arc.chain" field
##  found in a locally generated Authentication-Results header.
##
##  This list will be concatenated with DomainWhitelist (if provided).
##
# 
# DomainWhitelistFile /usr/local/etc/opendmarc/whitelist.domains
DomainWhitelistFile /etc/opendmarc/whitelist.domains
```
The `/etc/opendmarc/whitelist.domains` file contains the list of trusted domains. If an email is ARC-signed by one of the mail providers whose domain is on that list and the ARC signatures are validated by the receiving mail server, then the receiving server will accept the incoming email even if it fails SPF and/or DKIM validation.

The content of the `/etc/opendmarc/whitelist.domains` file can be:
```
google.com
gmail.com
googlegroups.com
messagingengine.com
pobox.com
topicbox.com
umich.edu
fastmail.com
fastmail.fm
one.com
securemx.jp
zone.eu
```
With the exception of zone.eu, all these domains are suggested [here](https://github.com/trusteddomainproject/ARC_Community_Sealers/blob/master/community_sealer_whitelist).

**Comment by lucas-oliver-trondsen** [comment]
Thank you, flowerysong, for version 1.1.0 which I think is the best version of OpenARC in existence at this moment.

If anyone wants to know how OpenARC v1.1.0 can be compiled, installed and configured on Debian 12, so that it works in conjunction with OpenDMARC and Postfix, [here](https://www.doublebastion.com/install-the-mail-server/#set-up-arc) is a detailed guide on how to do it.
