### ISSUE TITLE
Improve error message when LDFLAG "-Wl,-z,cet-report=error" is set

### ISSUE THREAD

**Issue by lquidfire** [flowerysong/OpenARC#23]
The LDFLAG `-Wl,-z,cet-report=error` can help debug why software is not built with `SHSTK`/`IBT` support (which could be done via the CFLAG "-fcf-protection").

When I enabled `-Wl,-z,cet-report=error`, however, I could no longer configure `OpenARC`. The error was:
```
checking for libidn2... yes
checking for libmilter/mfapi.h... yes
checking for smfi_register in -lmilter... no
configure: error: Unable to find libmilter
==> ERROR: A failure occurred in build().
    Aborting...
```
The full [config.log](http://0x0.st/XdsY.txt) is posted online.

It turned out that `libmilter` was not built with `SHSTK`/`IBT` support on my system. As a result, `OpenARC` could not be built with `SHSTK`/`IBT`, either, as all dependencies need to be built with that support first. Either everything has `SHSTK`/`IBT` support, or it won't show.

I presume that `-Wl,-z,cet-report=error` threw an error for `libmilter`, and as a result it ~somehow~ was no longer usable/visible for the `OpenARC` configure.

Would it be possible to write a Test that checks whether a LDFLAG `-Wl,-z,cet-report=error` is set, and if so, if there is an error along the line of `configure: error: Unable to find libmilter`, that a different error message to the current message is given?

Since I am not sure what exactly happens when `-Wl,-z,cet-report=error` spots an issue, I am not sure what the message should be. But perhaps it can contain a hint that it might be related to that flag? `error: Unable to find libmilter` was definitely not helpful in debugging.

[Here](https://bbs.archlinux.org/viewtopic.php?id=301000) is a link to a related discussion on the Archlinux forums.

**Comment by flowerysong** [comment]
That's what `config.log` is for.

```
mold: error: /usr/lib/libmilter.a(main.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_IBT
mold: error: /usr/lib/libmilter.a(main.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_SHSTK
mold: error: /usr/lib/libmilter.a(engine.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_IBT
mold: error: /usr/lib/libmilter.a(engine.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_SHSTK
mold: error: /usr/lib/libmilter.a(listener.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_IBT
mold: error: /usr/lib/libmilter.a(listener.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_SHSTK
mold: error: /usr/lib/libmilter.a(worker.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_IBT
mold: error: /usr/lib/libmilter.a(worker.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_SHSTK
mold: error: /usr/lib/libmilter.a(comm.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_IBT
mold: error: /usr/lib/libmilter.a(comm.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_SHSTK
mold: error: /usr/lib/libmilter.a(signal.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_IBT
mold: error: /usr/lib/libmilter.a(signal.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_SHSTK
mold: error: /usr/lib/libmilter.a(sm_gethost.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_IBT
mold: error: /usr/lib/libmilter.a(sm_gethost.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_SHSTK
mold: error: /usr/lib/libmilter.a(errstring.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_IBT
mold: error: /usr/lib/libmilter.a(errstring.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_SHSTK
mold: error: /usr/lib/libmilter.a(strl.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_IBT
mold: error: /usr/lib/libmilter.a(strl.o): -cet-report=error: missing GNU_PROPERTY_X86_FEATURE_1_SHSTK
```

**Comment by lquidfire** [comment]
Correct. I did find the actual error, and was able to fix it.

However, because `OpenARC` could find `libmilter` just find without the `-Wl,-z,cet-report=error` flag enabled, I was confused at first. That is why I thought a different error message might be more helpful.

If you don't think it's worth it, I understand. Not many people will enable that flag, and if one does, one should be on the lookout for its results anyway.

**Comment by flowerysong** [comment]
There are a lot of compilation flags you can provide that will break various `configure` checks, I don't think trying to special-case any particular one is worthwhile.

**Comment by lquidfire** [comment]
Okay, thank you for your reply.
